title: "GIS & Data Analysis Portfolio"
description: "A showcase of spatial analysis, hydrology, and environmental research"
theme: minima
author: Your Name
markdown: kramdown
baseurl: "" # Leave this empty if deploying to https://username.github.io/repo-name
